name: attraktorwiki
include:
  - compose.configs.yaml

services:
  mariadb:
    extends:
      file: compose.common.yaml
      service: mariadb
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:?attraktorwiki}
      - MYSQL_USER=${MYSQL_USER:?attraktorwiki}
      - MYSQL_PASSWORD=${SERVICE_PASSWORD_DBUSERPW:?}
      - MYSQL_ROOT_PASSWORD=${SERVICE_PASSWORD_DBROOTPW:?}
    volumes:
      - mediawiki-mysql:/var/lib/mysql
      - ./shared:/mnt/shared:ro
      - ./backup/attraktorwiki/mariadb:/mnt/backups:rw
  mediawiki:
    extends:
      file: compose.common.yaml
      service: mediawiki
    ports:
      - "8080:80"
    volumes:
      - mediawiki-composer-cache:/var/www/html/.composer/cache
      - ./shared:/mnt/shared:ro
      - ./backup/attraktorwiki/mediawiki:/mnt/backups:rw
      - ./images:/var/www/html/images:rw
      - ./skins/attraktor:/var/www/html/skins/attraktor
      - ./configs/composer.local.json:/var/www/html/composer.local.json
      - ./configs/LocalSettings.php:/var/www/html/LocalSettings.php

volumes:
  mediawiki-mysql:
  mediawiki-composer-cache:

networks:
  default:
    driver: bridge
