# compose.yaml - local deployment overrides with bind mounts for development

name: attraktorwiki

services:
  mariadb:
    extends:
      file: compose.common.yaml
      service: mariadb
    volumes:
      - ./backups/attraktorwiki:/mnt/backups
  mediawiki:
    extends:
      file: compose.common.yaml
      service: mediawiki
    ports:
      - "8080:80"
    volumes:
      - ./backups/attraktorwiki:/mnt/backups
      - ./images:/var/www/html/images
      - ./skins/attraktor:/var/www/html/skins/attraktor
      - ./configs/composer.local.json:/var/www/html/composer.local.json
      - ./configs/LocalSettings.php:/var/www/html/LocalSettings.php
      - ./configs/.htaccess:/var/www/html/.htaccess
      - ./configs/robots.txt:/var/www/html/robots.txt
volumes:
  mediawiki-mysql:

networks:
  default:
    driver: bridge

configs:
  mediawiki_secrets:
    content: |
      <?php
      $$wgSecretKey   = "${SERVICE_PASSWORD_64_APPSECRET:?error}";
      $$wgServer      = "${SERVICE_URL_MEDIAWIKI:?error}";
      $$wgFQDN        = "${SERVICE_FQDN_MEDIAWIKI:?error}";
      $$wgDBtype      = "mysql";
      $$wgDBserver    = "${SERVICE_NAME_MARIADB:?error}";
      $$wgDBname      = "${MYSQL_DATABASE:-attraktorwiki}";
      $$wgDBuser      = "${MYSQL_USER:-attraktorwiki}";
      $$wgDBpassword  = "${SERVICE_PASSWORD_DBUSERPW:?error}";
      $$phpDebug      = "${MW_PHP_DEBUG:-true}";
      $$wgReadonly    = "${MW_READONLY:-false}";
      $$wgSMTP = [
        'host'      => "${SMTP_HOST:-}",
        'IDHost'    => "${SMTP_IDHOST:-}",
        'port'      => ${SMTP_PORT:-587},
        'auth'      => ${SMTP_AUTH:-true},
        'username'  => "${SMTP_USERNAME:-}",
        'password'  => "${SMTP_PASSWORD:-}"
      ];
