# compose.coolify.yaml - contains overrides for coolify deployment and specific syntax

name: attraktorwiki

services:
  mariadb:
    extends:
      file: compose.common.yaml
      service: mariadb
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:?attraktorwiki}
      - MYSQL_USER=${MYSQL_USER:?attraktorwiki}
      - MYSQL_PASSWORD=${SERVICE_PASSWORD_DBUSERPW:?}
      - MYSQL_ROOT_PASSWORD=${SERVICE_PASSWORD_DBROOTPW:?}
    volumes:
      - /mnt/backups/attraktorwiki:/mnt/backups
  mediawiki:
    extends:
      file: compose.common.yaml
      service: mediawiki
    environment:
      - MYSQL_HOST=${SERVICE_NAME_MARIADB}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${SERVICE_PASSWORD_DBUSERPW}
      - MEDIAWIKI_APPSECRET=${SERVICE_PASSWORD_64_APPSECRET:?}
      - SMTP_HOST=${SMTP_HOST:?}
      - SMTP_IDHOST=${SMTP_IDHOST:?}
      - SMTP_PORT=${SMTP_PORT:?587}
      - SMTP_AUTH=${SMTP_AUTH:?true}
      - SMTP_USERNAME=${SMTP_USERNAME:?}
      - SMTP_PASSWORD=${SMTP_PASSWORD:?}
    volumes:
      - mediawiki-images:/var/www/html/images
      - /mnt/backups/attraktorwiki:/mnt/backups

configs:
  mediawiki_secrets:
    content: |
      <?php
      $$wgSecretKey   = "${SERVICE_PASSWORD_64_APPSECRET}";
      $$wgServer      = "${SERVICE_URL_MEDIAWIKI}";
      $$wgFQDN        = "${SERVICE_FQDN_MEDIAWIKI}";
      $$wgDBtype      = "mysql";
      $$wgDBserver    = "${SERVICE_NAME_MARIADB}";
      $$wgDBname      = "${MYSQL_DATABASE}";
      $$wgDBuser      = "${MYSQL_USER}";
      $$wgDBpassword  = "${SERVICE_PASSWORD_DBUSERPW}";
      $$phpDebug      = "${MW_PHP_DEBUG}";
      $$wgReadonly    = "${MW_READONLY}";
      $$wgSMTP = [
        'host'      => "${SMTP_HOST}",
        'IDHost'    => "${SMTP_IDHOST}",
        'port'      => ${SMTP_PORT},
        'auth'      => ${SMTP_AUTH},
        'username'  => "${SMTP_USERNAME}",
        'password'  => "${SMTP_PASSWORD}"
      ];
