name: attraktorwiki

services:
  mariadb:
    image: mariadb:11.8
    container_name: attr_mariadb
    restart: unless-stopped
  mediawiki:
    build:
      context: .
      tags:
        - "attraktorwiki:1.43"
    container_name: attr_mediawiki
    restart: unless-stopped
    depends_on:
      - mariadb
    configs:
      - source: mediawiki_secrets
        target: /var/www/data/LocalSecrets.php      
