name: attraktorwiki
include:
  - compose.configs.yaml
services:
  mariadb:
    image: mariadb:lts
    container_name: attr_mariadb
    restart: unless-stopped
    configs:
      - source: backup_db_script
        target: /usr/local/bin/backup_db.sh
    volumes:
      - mediawiki-mysql:/var/lib/mysql
      # - ./scripts/backup_db.sh:/usr/local/bin/backup_db.sh

  mediawiki:
    build: .
    container_name: attr_mediawiki
    restart: unless-stopped
    depends_on:
      - mariadb
    configs:
      - source: mediawiki_secrets
        target: /var/www/data/LocalSecrets.php
    volumes:
      - 'mediawiki-images:/var/www/html/images'
      - 'mediawiki-composer-cache:/var/www/html/.composer/cache'
      # - ./scripts/backup_images.sh:/usr/local/bin/backup_images.sh
