name: attraktorwiki
include:
  - compose.configs.yaml
configs:
  mediawiki_secrets:
    external: true
services:
  mariadb:
    extends:
      file: compose.common.yaml
      service: mariadb
    volumes:
      - mediawiki-mysql:/var/lib/mysql
      - /mnt/shared:/mnt/shared:ro
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
  mediawiki:
    extends:
      file: compose.common.yaml
      service: mediawiki
    volumes:
      - 'mediawiki-images:/var/www/html/images'
      - 'mediawiki-composer-cache:/var/www/html/.composer/cache'
      - /mnt/shared:/mnt/shared:ro
      - /mnt/backups/attraktorwiki:/mnt/backups:rw
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:80'
      interval: 5s
      timeout: 20s
      retries: 10

