name: attraktorwiki

configs:
  mediawiki_secrets:
    content: |
      <?php
      $$wgSecretKey   = "${MEDIAWIKI_SECRET_KEY}";
      $$wgServer      = "${COOLIFY_URL}";
      $$wgFQDN        = "${COOLIFY_FQDN}";
      $$wgDBtype      = "mysql";
      $$wgDBserver    = "${SERVICE_NAME_MARIADB}";
      $$wgDBname      = "${MYSQL_DATABASE}";
      $$wgDBuser      = "${MYSQL_USER}";
      $$wgDBpassword  = "${MYSQL_PASSWORD}";
      // $$wgSMTP = [
      //     'host'      => "${SMTP_HOST}",
      //     'IDHost'    => "${SMTP_IDHOST}",
      //     'port'      => ${SMTP_PORT},
      //     'auth'      => true,
      //     'username'  => "${SMTP_USERNAME}",
      //     'password'  => "${SMTP_PASSWORD}"
      // ];
      
services:
  mariadb:
    image: mariadb:lts
    container_name: attr_mariadb
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    volumes:
      - mediawiki-mysql:/var/lib/mysql

  mediawiki:
    build: .
    container_name: attr_mediawiki
    restart: unless-stopped
    depends_on:
      - mariadb
    configs:
      - source: mediawiki_secrets
        target: /var/www/data/LocalSecrets.php
    volumes:
      - 'mediawiki-images:/var/www/html/images'
      - 'mediawiki-composer-cache:/var/www/html/.composer/cache'
      # - ./skins/attraktor:/var/www/html/skins/attraktor
      # - ./composer.local.json:/var/www/html/composer.local.json
      # - ./LocalSettings.php:/var/www/html/LocalSettings.php


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: attr_phpmyadmin
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      PMA_HOST: ${SERVICE_NAME_MARIADB}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

volumes:
  mediawiki-images:
  mediawiki-mysql:
  mediawiki-composer-cache:

networks:
  default:
    driver: bridge
