configs:
  mediawiki_secrets:
    content: |
      <?php
      $$wgSecretKey   = "${SERVICE_PASSWORD_64_APPSECRET}";
      $$wgServer      = "${SERVICE_URL_MEDIAWIKI}";
      $$wgFQDN        = "${SERVICE_FQDN_MEDIAWIKI}";
      $$wgDBtype      = "mysql";
      $$wgDBserver    = "${SERVICE_NAME_MARIADB}";
      $$wgDBname      = "${MYSQL_DATABASE}";
      $$wgDBuser      = "${MYSQL_USER}";
      $$wgDBpassword  = "${SERVICE_PASSWORD_DBUSERPW}";
      $$wgSMTP = [
        'host'      => "${SMTP_HOST}",
        'IDHost'    => "${SMTP_IDHOST}",
        'port'      => ${SMTP_PORT},
        'auth'      => ${SMTP_AUTH},
        'username'  => "${SMTP_USERNAME}",
        'password'  => "${SMTP_PASSWORD}"
      ];
