name: attraktorwiki

configs:
  mediawiki_secrets:
    content: |
      <?php
      $$wgSecretKey   = "${SERVICE_PASSWORD_64_APPSECRET:?}";
      $$wgServer      = "${SERVICE_URL_MEDIAWIKI:?}";
      $$wgFQDN        = "${SERVICE_FQDN_MEDIAWIKI:?}";
      $$wgDBtype      = "mysql";
      $$wgDBserver    = "${SERVICE_NAME_MARIADB:?}";
      $$wgDBname      = "${DBNAME:?}";
      $$wgDBuser      = "${DBUSER:?}";
      $$wgDBpassword  = "${SERVICE_PASSWORD_DBUSERPW:?}";
      $$wgSMTP = [
        'host'      => "${SMTP_HOST:?}",
        'IDHost'    => "${SMTP_IDHOST:?}",
        'port'      => ${SMTP_PORT:?587},
        'auth'      => ${SMTP_AUTH:?true},
        'username'  => "${SMTP_USERNAME:?}",
        'password'  => "${SMTP_PASSWORD:?}"
      ];

services:
  mariadb:
    extends:
      file: compose.common.yaml
      service: mariadb
    environment:
      - MYSQL_DATABASE=${DBNAME:?attraktorwiki}
      - MYSQL_USER=${DBUSER:?attraktorwiki}
      - MYSQL_PASSWORD=${SERVICE_PASSWORD_DBUSERPW:?}
      - MYSQL_ROOT_PASSWORD=${SERVICE_PASSWORD_DBROOTPW:?}
    volumes:
      - mediawiki-mysql:/var/lib/mysql
      - /mnt/shared:/mnt/shared:ro
  mediawiki:
    extends:
      file: compose.common.yaml
      service: mediawiki
    configs:
      - source: mediawiki_secrets
        target: /var/www/data/LocalSecrets.php
    volumes:
      - 'mediawiki-images:/var/www/html/images'
      - 'mediawiki-composer-cache:/var/www/html/.composer/cache'
      - /mnt/shared:/mnt/shared:ro
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:80'
      interval: 5s
      timeout: 20s
      retries: 10

